<?php /** @var $block \Bforward\PickUpProductFromShop\Block\Adminhtml\Order\AbstractOrder*/ ?>
<?php $order = $block->getOrder() ?>
<?php if ($order->getIsVirtual()) : return '';endif; ?>

<?php /* Shipping Method */ ?>
<div class="admin__page-section-item order-shipping-method">
    <div class="admin__page-section-item-title">
        <span class="title"><?= /* @escapeNotVerified */ __('Shipping &amp; Handling Information') ?></span>
    </div>
    <div class="admin__page-section-item-content">
        <?php  if ($order->getTracksCollection()->count()) : ?>
            <p><a href="#" id="linkId" onclick="popWin('<?= /* @escapeNotVerified */ $this->helper('Magento\Shipping\Helper\Data')->getTrackingPopupUrlBySalesModel($order) ?>','trackorder','width=800,height=600,resizable=yes,scrollbars=yes')" title="<?= /* @escapeNotVerified */ __('Track Order') ?>"><?= /* @escapeNotVerified */ __('Track Order') ?></a></p>
        <?php endif; ?>
        <?php if ($order->getShippingDescription()): ?>
            <strong><?= $block->escapeHtml($order->getShippingDescription()) ?></strong>

            <?php if ($this->helper('Magento\Tax\Helper\Data')->displayShippingPriceIncludingTax()): ?>
                <?php $_excl = $block->displayShippingPriceInclTax($order); ?>
            <?php else: ?>
                <?php $_excl = $block->displayPriceAttribute('shipping_amount', false, ' '); ?>
            <?php endif; ?>
            <?php $_incl = $block->displayShippingPriceInclTax($order); ?>

            <?= /* @escapeNotVerified */ $_excl ?>
            <?php if ($this->helper('Magento\Tax\Helper\Data')->displayShippingBothPrices() && $_incl != $_excl): ?>
                (<?= /* @escapeNotVerified */ __('Incl. Tax') ?> <?= /* @escapeNotVerified */ $_incl ?>)
            <?php endif; ?>

            <!-- Info about shop for picking up -->
            <?php if ($order->getPickupShopId()): ?>
                <?php /** @var $pickupShop \Bforward\PickUpProductFromShop\Model\ShopList */ ?>
                <?php $pickupShop = $block->getPickupShop(); ?>
                <div class="admin__page-section-item-content-pickupshop">
                    <strong><?= __('Shop info:') ?></strong><br>
                    <?= __('Name:') ?> <?= $pickupShop->getName() ?><br>
                    <?= __('Address:')?> <?= $pickupShop->getAddress() ?><br>
                    <?= __('Email:') ?> <a href="mailto:<?= $pickupShop->getEmail() ?>"><?= $pickupShop->getEmail() ?></a><br>
                    <?= __('Phone number:') ?><a href="tel:<?= $pickupShop->getPhoneNumber() ?>"> <?= $pickupShop->getPhoneNumber() ?></a>
                </div>
            <?php endif; ?>

        <?php else: ?>
            <?= /* @escapeNotVerified */ __('No shipping information available') ?>
        <?php endif; ?>
    </div>
</div>
